import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { FC, ReactNode } from "react";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import { CategoryText } from "@/components/CategoryLink";
import { Toaster } from "@/components/ui/toaster";
import { Sell_btn } from "@/components/Sell_btn";

const fontSans = FontSans({
  subsets: ["cyrillic-ext"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "LOX - Buy & Sell Products anywhere in Pakistan",
  description: "Generated by create next app",
  keywords: "LOX, Buy, Sell, Products, Pakistan",
};

interface LayoutProps {
  children: ReactNode;
}

const RootLayout: FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        id="top"
        className={cn(
          "min-h-screen bg-background text-foreground font-sans antialiased xl:container flex flex-col justify-between",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div>
            <Sell_btn className="fixed bottom-3 left-1/2 transform -translate-x-1/2 xmd:hidden z-50" />

            <Navbar />
            <CategoryText />

            {children}
          </div>
          <div className="">
            <Footer />
          </div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
};
export default RootLayout;
