import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { FC, ReactNode } from "react";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "next-themes";

const fontSans = FontSans({
  subsets: ["cyrillic-ext"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "LOX - Buy & Sell Products anywhere in Pakistan",
  description: "Generated by create next app",
  keywords: "LOX, Buy, Sell, Products, Pakistan",
};

interface LayoutProps {
  children: ReactNode;
}

const RootLayout: FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background text-foreground font-sans antialiased xl:container",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <footer>
            {" "}
            <p className="text-2xl">footer</p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
};
export default RootLayout;
